### Register user
POST http://localhost/projekbasdat/auth/register.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678 &
nama = farhan &
email = farhankebab@gmail.com

### Register user invalid
POST http://localhost/projekbasdat/auth/register.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678 &
name = farhan &
email = tes@gmail.com

### Login user
POST http://localhost/projekbasdat/auth/login.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678

### Login user invalid
POST http://localhost/projekbasdat/auth/login.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 1234567891011

### Check library
GET http://localhost/projekbasdat/library/check.php/?username=farhandenai&anime_id=9253
Accept: application/json

### Read library
GET http://localhost/projekbasdat/library/read.php/farhandenai
Accept: application/json

### Read review
GET http://localhost/projekbasdat/review/read.php/farhandenai
Accept: application/json

### Read all review
GET http://localhost/projekbasdat/review/readAll.php
Accept: application/json

### Read anime review
GET https://localhost/projekbasdat/review/anime.php/52991
Accept: application/json

### Delete review
DELETE http://localhost/projekbasdat/review/delete.php/1
Accept: application/json