### Register user

POST http://192.168.1.4/projekbasdat/auth/register.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678 &
nama = farhan &
email = farhankebab@gmail.com

### Register user invalid

POST http://192.168.1.4/projekbasdat/auth/register.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678 &
name = farhan &
email = tes@gmail.com

### Login user

POST http://192.168.1.4/projekbasdat/auth/login.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 12345678

### Login user invalid

POST http://192.168.1.4/projekbasdat/auth/login.php
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = farhankebab &
password = 1234567891011

### Check library

GET http://192.168.1.4/projekbasdat/library/check.php/?username=farhandenai&anime_id=9253
Accept: application/json

### Read library

GET http://192.168.1.4/projekbasdat/library/read.php/farhandenai
Accept: application/json

### Read review
GET http://192.168.1.4/projekbasdat/review/read.php/farhandenai
Accept: application/json

### Read All Review
GET http://192.168.1.4/projekbasdat/review/readAll.php
Accept: application/json

### Delete review
DELETE http://192.168.1.4/projekbasdat/review/delete.php/1
Accept: application/json